"""Mühendislik Fakültesi GERÇEK bölüm + öğretim üyesi seed'i (K-50/K-52).

Bu dosya dev veritabanından ÜRETİLDİ: siteden içe aktarılan öğretim üyeleri
(Jeoloji hariç) ve elle eklenen bölümler. Amaç: DB sıfırlansa da bu gerçek
kadroyu tek komutla geri yüklemek. Örnek/demo verisi (seed_data.py) DEĞİL.

Ayrıca bir TEST ALT HESABI ekler (kısıtlı yetki testleri için).

Çalıştırma:  python seed_engineering.py
İdempotent: var olan kayıtları (kod / normalized_name / e-posta) atlar.
"""
from app.db import SessionLocal
from app.models import Department, Lecturer, User, UserRole, UserStatus, Workgroup
from app.security import hash_password

DEPARTMENTS = [{'code': 'CE', 'name': 'İnşaat Mühendisliği'},
 {'code': 'CENG', 'name': 'Bilgisayar Mühendisliği'},
 {'code': 'EEE', 'name': 'Elektrik-Elektronik Mühendisliği'},
 {'code': 'MINE', 'name': 'Maden Mühendisliği'},
 {'code': 'MME', 'name': 'Metalurji ve Malzeme Mühendisliği'},
 {'code': 'SE', 'name': 'Yazılım Mühendisliği'}]

LECTURERS = [{'full_name': 'Ahmet Deniz BAŞ',
  'title': 'Doç. Dr.',
  'normalized_name': 'ahmet deniz baş',
  'email': 'denizbas@mu.edu.tr',
  'is_external': False,
  'source': 'IMPORT',
  'duty_unit': 'Yatağan Meslek Yüksekokulu',
  'cadre_unit': 'Maden Mühendisliği',
  'dept_code': 'MINE'},
 {'full_name': 'Ali Arslan KAYA',
  'title': 'Prof. Dr.',
  'normalized_name': 'ali arslan kaya',
  'email': 'aakaya@mu.edu.tr',
  'is_external': False,
  'source': 'IMPORT',
  'duty_unit': 'Metalurji Ve Malzeme Mühendisliği',
  'cadre_unit': 'Metalurji Ve Malzeme Mühendisliği',
  'dept_code': 'MME'},
 {'full_name': 'Ali Can ERÜST',
  'title': 'Araş.Gör.Dr.',
  'normalized_name': 'ali can erüst',
  'email': 'alicanerust@mu.edu.tr',
  'is_external': False,
  'source': 'IMPORT',
  'duty_unit': 'Elektrik Elektronik Mühendisliği',
  'cadre_unit': 'Elektrik Elektronik Mühendisliği',
  'dept_code': 'EEE'},
 {'full_name': 'Ali Umut ÖZCAN',
  'title': 'Arş. Gör.',
  'normalized_name': 'ali umut özcan',
  'email': 'aliumutozcan@mu.edu.tr',
  'is_external': False,
  'source': 'IMPORT',
  'duty_unit': 'Elektrik Elektronik Mühendisliği',
  'cadre_unit': 'Elektrik Elektronik Mühendisliği',
  'dept_code': 'EEE'},
 {'full_name': 'Altuğ SAYGILI',
  'title': 'Doç. Dr.',
  'normalized_name': 'altuğ saygılı',
  'email': 'saygili@mu.edu.tr',
  'is_external': False,
  'source': 'IMPORT',
  'duty_unit': 'İnşaat Mühendisliği',
  'cadre_unit': 'İnşaat Mühendisliği',
  'dept_code': 'CE'},
 {'full_name': 'Arda Can Mertkal KÖROĞLU',
  'title': 'Arş. Gör.',
  'normalized_name': 'arda can mertkal köroğlu',
  'email': 'ardakoroglu@mu.edu.tr',
  'is_external': False,
  'source': 'IMPORT',
  'duty_unit': 'Bilgisayar Mühendisliği',
  'cadre_unit': 'Bilgisayar Mühendisliği',
  'dept_code': 'CENG'},
 {'full_name': 'Aslı ÇAKIR',
  'title': 'Doç. Dr.',
  'normalized_name': 'aslı çakır',
  'email': 'cakir@mu.edu.tr',
  'is_external': False,
  'source': 'IMPORT',
  'duty_unit': 'Metalurji Ve Malzeme Mühendisliği',
  'cadre_unit': 'Metalurji Ve Malzeme Mühendisliği',
  'dept_code': 'MME'},
 {'full_name': 'Avni GÜNEY',
  'title': 'Prof. Dr.',
  'normalized_name': 'avni güney',
  'email': 'aguney@mu.edu.tr',
  'is_external': False,
  'source': 'IMPORT',
  'duty_unit': 'Maden Mühendisliği',
  'cadre_unit': 'Maden Mühendisliği',
  'dept_code': 'MINE'},
 {'full_name': 'Ayşe Kaya',
  'title': 'Doç. Dr.',
  'normalized_name': 'ayşe kaya',
  'email': None,
  'is_external': False,
  'source': 'IMPORT',
  'duty_unit': None,
  'cadre_unit': None,
  'dept_code': 'CENG'},
 {'full_name': 'Aysu GÖÇÜGENCİ',
  'title': 'Araş.Gör.Dr.',
  'normalized_name': 'aysu göçügenci',
  'email': 'aysugocugenci@mu.edu.tr',
  'is_external': False,
  'source': 'IMPORT',
  'duty_unit': 'İnşaat Mühendisliği',
  'cadre_unit': 'İnşaat Mühendisliği',
  'dept_code': 'CE'},
 {'full_name': 'Bahadır Süleyman YILDIRIM',
  'title': 'Prof. Dr.',
  'normalized_name': 'bahadır süleyman yıldırım',
  'email': 'bahadir.yildirim@mu.edu.tr',
  'is_external': False,
  'source': 'IMPORT',
  'duty_unit': 'Elektrik Elektronik Mühendisliği',
  'cadre_unit': 'Elektrik Elektronik Mühendisliği',
  'dept_code': 'EEE'},
 {'full_name': 'Barış Ethem SÜZEK',
  'title': 'Doç. Dr.',
  'normalized_name': 'barış ethem süzek',
  'email': 'barissuzek@mu.edu.tr',
  'is_external': False,
  'source': 'IMPORT',
  'duty_unit': 'Bilgisayar Mühendisliği',
  'cadre_unit': 'Bilgisayar Mühendisliği',
  'dept_code': 'CENG'},
 {'full_name': 'Barış İŞÇİ PEMBECİ',
  'title': 'Dr. Öğr. Üyesi',
  'normalized_name': 'barış işçi pembeci',
  'email': 'barispembeci@mu.edu.tr',
  'is_external': False,
  'source': 'IMPORT',
  'duty_unit': 'Bilgisayar Mühendisliği',
  'cadre_unit': 'Sanat Tarihi',
  'dept_code': 'CENG'},
 {'full_name': 'Bekir Taner DİNÇER',
  'title': 'Prof. Dr.',
  'normalized_name': 'bekir taner dinçer',
  'email': 'dtaner@mu.edu.tr',
  'is_external': False,
  'source': 'IMPORT',
  'duty_unit': 'Bilgisayar Mühendisliği',
  'cadre_unit': 'Bilgisayar Mühendisliği',
  'dept_code': 'CENG'},
 {'full_name': 'Berke PİŞKİN',
  'title': 'Doç. Dr.',
  'normalized_name': 'berke pişkin',
  'email': 'berkepiskin@mu.edu.tr',
  'is_external': False,
  'source': 'IMPORT',
  'duty_unit': 'Metalurji Ve Malzeme Mühendisliği',
  'cadre_unit': 'Metalurji Ve Malzeme Mühendisliği',
  'dept_code': 'MME'},
 {'full_name': 'Can Şahin',
  'title': 'Dr.',
  'normalized_name': 'can şahin',
  'email': None,
  'is_external': False,
  'source': 'IMPORT',
  'duty_unit': None,
  'cadre_unit': None,
  'dept_code': 'CENG'},
 {'full_name': 'Ceren KÜÇÜKUYSAL',
  'title': 'Doç. Dr.',
  'normalized_name': 'ceren küçükuysal',
  'email': 'cerenkucukuysal@mu.edu.tr',
  'is_external': False,
  'source': 'IMPORT',
  'duty_unit': 'Maden Mühendisliği',
  'cadre_unit': 'Maden Mühendisliği',
  'dept_code': 'MINE'},
 {'full_name': 'Ceyhun ÖZÇELİK',
  'title': 'Doç. Dr.',
  'normalized_name': 'ceyhun özçelik',
  'email': 'cozcelik@mu.edu.tr',
  'is_external': False,
  'source': 'IMPORT',
  'duty_unit': 'İnşaat Mühendisliği',
  'cadre_unit': 'İnşaat Mühendisliği',
  'dept_code': 'CE'},
 {'full_name': 'Cihat ÇETİNKAYA',
  'title': 'Dr. Öğr. Üyesi',
  'normalized_name': 'cihat çetinkaya',
  'email': 'cihat@mu.edu.tr',
  'is_external': False,
  'source': 'IMPORT',
  'duty_unit': 'Yazılım Mühendisliği',
  'cadre_unit': 'Yazılım Mühendisliği',
  'dept_code': 'SE'},
 {'full_name': 'Çınar ÖNCEL',
  'title': 'Dr. Öğr. Üyesi',
  'normalized_name': 'çınar öncel',
  'email': 'cinaroncel@mu.edu.tr',
  'is_external': False,
  'source': 'IMPORT',
  'duty_unit': 'Metalurji Ve Malzeme Mühendisliği',
  'cadre_unit': 'Metalurji Ve Malzeme Mühendisliği',
  'dept_code': 'MME'},
 {'full_name': 'Deniz ÜLGEN',
  'title': 'Prof. Dr.',
  'normalized_name': 'deniz ülgen',
  'email': 'denizulgen@mu.edu.tr',
  'is_external': False,
  'source': 'IMPORT',
  'duty_unit': 'Rektörlük',
  'cadre_unit': 'İnşaat Mühendisliği',
  'dept_code': 'CE'},
 {'full_name': 'Ebru HARMANDAR',
  'title': 'Doç. Dr.',
  'normalized_name': 'ebru harmandar',
  'email': 'ebruharmandar@mu.edu.tr',
  'is_external': False,
  'source': 'IMPORT',
  'duty_unit': 'İnşaat Mühendisliği',
  'cadre_unit': 'İnşaat Mühendisliği',
  'dept_code': 'CE'},
 {'full_name': 'Elif AKGÜL',
  'title': 'Öğr. Gör.',
  'normalized_name': 'elif akgül',
  'email': 'elifakgul@mu.edu.tr',
  'is_external': False,
  'source': 'IMPORT',
  'duty_unit': 'Maden Mühendisliği',
  'cadre_unit': 'Maden Mühendisliği',
  'dept_code': 'MINE'},
 {'full_name': 'Elif Arslan',
  'title': 'Dr.',
  'normalized_name': 'elif arslan',
  'email': None,
  'is_external': False,
  'source': 'IMPORT',
  'duty_unit': None,
  'cadre_unit': None,
  'dept_code': 'CENG'},
 {'full_name': 'Emine Elif TÜLAY',
  'title': 'Doç. Dr.',
  'normalized_name': 'emine elif tülay',
  'email': 'eliftulay@mu.edu.tr',
  'is_external': False,
  'source': 'IMPORT',
  'duty_unit': 'Yazılım Mühendisliği',
  'cadre_unit': 'Yazılım Mühendisliği',
  'dept_code': 'SE'},
 {'full_name': 'Emrah TELLİ',
  'title': 'Arş. Gör.',
  'normalized_name': 'emrah telli',
  'email': 'emrahtelli@mu.edu.tr',
  'is_external': False,
  'source': 'IMPORT',
  'duty_unit': 'Elektrik Elektronik Mühendisliği',
  'cadre_unit': 'Elektrik Elektronik Mühendisliği',
  'dept_code': 'EEE'},
 {'full_name': 'Emre DOĞU',
  'title': 'Arş. Gör.',
  'normalized_name': 'emre doğu',
  'email': 'emredogu@mu.edu.tr',
  'is_external': False,
  'source': 'IMPORT',
  'duty_unit': 'Yazılım Mühendisliği',
  'cadre_unit': 'Yazılım Mühendisliği',
  'dept_code': 'SE'},
 {'full_name': 'Enis KARAARSLAN',
  'title': 'Doç. Dr.',
  'normalized_name': 'enis karaarslan',
  'email': 'enis.karaarslan@mu.edu.tr',
  'is_external': False,
  'source': 'IMPORT',
  'duty_unit': 'Bilgisayar Mühendisliği',
  'cadre_unit': 'Bilgisayar Mühendisliği',
  'dept_code': 'CENG'},
 {'full_name': 'Ercan POLAT',
  'title': 'Araş.Gör.Dr.',
  'normalized_name': 'ercan polat',
  'email': 'epolat@mu.edu.tr',
  'is_external': False,
  'source': 'IMPORT',
  'duty_unit': 'Maden Mühendisliği',
  'cadre_unit': 'Maden Mühendisliği',
  'dept_code': 'MINE'},
 {'full_name': 'Erdem ŞAHİN',
  'title': 'Doç. Dr.',
  'normalized_name': 'erdem şahin',
  'email': 'erdemsahin@mu.edu.tr',
  'is_external': False,
  'source': 'IMPORT',
  'duty_unit': 'Metalurji Ve Malzeme Mühendisliği',
  'cadre_unit': 'Metalurji Ve Malzeme Mühendisliği',
  'dept_code': 'MME'},
 {'full_name': 'Erdem TÜRK',
  'title': 'Dr. Öğr. Üyesi',
  'normalized_name': 'erdem türk',
  'email': 'erdemturk@mu.edu.tr',
  'is_external': False,
  'source': 'IMPORT',
  'duty_unit': 'Bilgisayar Mühendisliği',
  'cadre_unit': 'Bilgisayar Mühendisliği',
  'dept_code': 'CENG'},
 {'full_name': 'Erkut TEKELİ',
  'title': 'Dr. Öğr. Üyesi',
  'normalized_name': 'erkut tekeli',
  'email': 'erkuttekeli@mu.edu.tr',
  'is_external': False,
  'source': 'IMPORT',
  'duty_unit': 'Yazılım Mühendisliği',
  'cadre_unit': 'Yazılım Mühendisliği',
  'dept_code': 'SE'},
 {'full_name': 'Ersan GÜRAY',
  'title': 'Dr. Öğr. Üyesi',
  'normalized_name': 'ersan güray',
  'email': 'ersan.guray@mu.edu.tr',
  'is_external': False,
  'source': 'IMPORT',
  'duty_unit': 'İnşaat Mühendisliği',
  'cadre_unit': 'İnşaat Mühendisliği',
  'dept_code': 'CE'},
 {'full_name': 'Fatih PİŞKİN',
  'title': 'Doç. Dr.',
  'normalized_name': 'fatih pişkin',
  'email': 'fatihpiskin@mu.edu.tr',
  'is_external': False,
  'source': 'IMPORT',
  'duty_unit': 'Metalurji Ve Malzeme Mühendisliği',
  'cadre_unit': 'Metalurji Ve Malzeme Mühendisliği',
  'dept_code': 'MME'},
 {'full_name': 'Gülhan ÇAKMAK',
  'title': 'Prof. Dr.',
  'normalized_name': 'gülhan çakmak',
  'email': 'gulhancakmak@mu.edu.tr',
  'is_external': False,
  'source': 'IMPORT',
  'duty_unit': 'Metalurji Ve Malzeme Mühendisliği',
  'cadre_unit': 'Metalurji Ve Malzeme Mühendisliği',
  'dept_code': 'MME'},
 {'full_name': 'Hande AKA UYMAZ',
  'title': 'Dr. Öğr. Üyesi',
  'normalized_name': 'hande aka uymaz',
  'email': 'handeakauymaz@mu.edu.tr',
  'is_external': False,
  'source': 'IMPORT',
  'duty_unit': 'Bilgisayar Mühendisliği',
  'cadre_unit': 'Bilgisayar Mühendisliği',
  'dept_code': 'CENG'},
 {'full_name': 'Hasan Ali ÖZKAN',
  'title': 'Arş. Gör.',
  'normalized_name': 'hasan ali özkan',
  'email': 'hasanaliozkan@mu.edu.tr',
  'is_external': False,
  'source': 'IMPORT',
  'duty_unit': 'Yazılım Mühendisliği',
  'cadre_unit': 'Yazılım Mühendisliği',
  'dept_code': 'SE'},
 {'full_name': 'Hasan YİĞİT',
  'title': 'Arş. Gör.',
  'normalized_name': 'hasan yiğit',
  'email': 'hasanyigit@mu.edu.tr',
  'is_external': False,
  'source': 'IMPORT',
  'duty_unit': 'Yazılım Mühendisliği',
  'cadre_unit': 'Yazılım Mühendisliği',
  'dept_code': 'SE'},
 {'full_name': 'Hayriye Serra ALTINOLUK',
  'title': 'Dr. Öğr. Üyesi',
  'normalized_name': 'hayriye serra altınoluk',
  'email': 'serraltinoluk@mu.edu.tr',
  'is_external': False,
  'source': 'IMPORT',
  'duty_unit': 'Elektrik Elektronik Mühendisliği',
  'cadre_unit': 'Elektrik Elektronik Mühendisliği',
  'dept_code': 'EEE'},
 {'full_name': 'İbrahim Ferid ÖGE',
  'title': 'Prof. Dr.',
  'normalized_name': 'ibrahim ferid öge',
  'email': 'feridoge@mu.edu.tr',
  'is_external': False,
  'source': 'IMPORT',
  'duty_unit': 'Maden Mühendisliği',
  'cadre_unit': 'Maden Mühendisliği',
  'dept_code': 'MINE'},
 {'full_name': 'İlke EVRİM',
  'title': 'Öğr. Gör.',
  'normalized_name': 'ilke evrim',
  'email': 'ilketan@mu.edu.tr',
  'is_external': False,
  'source': 'IMPORT',
  'duty_unit': 'Bilgisayar Mühendisliği',
  'cadre_unit': 'Endüstri Mühendisliği',
  'dept_code': 'CENG'},
 {'full_name': 'İrem KARACA ULUOĞLU',
  'title': 'Arş. Gör.',
  'normalized_name': 'irem karaca uluoğlu',
  'email': 'iremkaracauluoglu@mu.edu.tr',
  'is_external': False,
  'source': 'IMPORT',
  'duty_unit': 'Bilgisayar Mühendisliği',
  'cadre_unit': 'Bilgisayar Mühendisliği',
  'dept_code': 'CENG'},
 {'full_name': 'İsmail Çağrı GÖRKEM',
  'title': 'Dr. Öğr. Üyesi',
  'normalized_name': 'ismail çağrı görkem',
  'email': 'cagrigorkem@mu.edu.tr',
  'is_external': False,
  'source': 'IMPORT',
  'duty_unit': 'İnşaat Mühendisliği',
  'cadre_unit': 'İnşaat Mühendisliği',
  'dept_code': 'CE'},
 {'full_name': 'Kutlu KARAYAHŞİ',
  'title': 'Dr. Öğr. Üyesi',
  'normalized_name': 'kutlu karayahşi',
  'email': 'kutlukarayahsi@mu.edu.tr',
  'is_external': False,
  'source': 'IMPORT',
  'duty_unit': 'Elektrik Elektronik Mühendisliği',
  'cadre_unit': 'Elektrik Elektronik Mühendisliği',
  'dept_code': 'EEE'},
 {'full_name': 'Mahmut TENRUH',
  'title': 'Doç. Dr.',
  'normalized_name': 'mahmut tenruh',
  'email': 'tmahmut@mu.edu.tr',
  'is_external': False,
  'source': 'IMPORT',
  'duty_unit': 'Elektrik Elektronik Mühendisliği',
  'cadre_unit': 'Elektrik Elektronik Mühendisliği',
  'dept_code': 'EEE'},
 {'full_name': 'Mehmed Emre ÖZDEMİR',
  'title': 'Arş. Gör.',
  'normalized_name': 'mehmed emre özdemir',
  'email': 'mehmedemreozdemir@mu.edu.tr',
  'is_external': False,
  'source': 'IMPORT',
  'duty_unit': 'Yazılım Mühendisliği',
  'cadre_unit': 'Yazılım Mühendisliği',
  'dept_code': 'SE'},
 {'full_name': 'Mehmet Demir',
  'title': 'Prof. Dr.',
  'normalized_name': 'mehmet demir',
  'email': None,
  'is_external': False,
  'source': 'IMPORT',
  'duty_unit': None,
  'cadre_unit': None,
  'dept_code': 'EEE'},
 {'full_name': 'Mehmet HANÇER',
  'title': 'Prof. Dr.',
  'normalized_name': 'mehmet hançer',
  'email': 'mehmethancer@mu.edu.tr',
  'is_external': False,
  'source': 'IMPORT',
  'duty_unit': 'Metalurji Ve Malzeme Mühendisliği',
  'cadre_unit': 'Metalurji Ve Malzeme Mühendisliği',
  'dept_code': 'MME'},
 {'full_name': 'Mehmet POYRAZ',
  'title': 'Öğr. Gör. Dr.',
  'normalized_name': 'mehmet poyraz',
  'email': 'mpoyraz@mu.edu.tr',
  'is_external': False,
  'source': 'IMPORT',
  'duty_unit': 'Metalurji Ve Malzeme Mühendisliği',
  'cadre_unit': 'Makine Mühendisliği',
  'dept_code': 'MME'},
 {'full_name': 'Mehmet Rifat KAHYAOĞLU',
  'title': 'Doç. Dr.',
  'normalized_name': 'mehmet rifat kahyaoğlu',
  'email': 'rkahyaoglu@mu.edu.tr',
  'is_external': False,
  'source': 'IMPORT',
  'duty_unit': 'İnşaat Mühendisliği',
  'cadre_unit': 'İnşaat Mühendisliği',
  'dept_code': 'CE'},
 {'full_name': 'Mervegül UYSAL',
  'title': 'Araş.Gör.Dr.',
  'normalized_name': 'mervegül uysal',
  'email': 'merveguluysal@mu.edu.tr',
  'is_external': False,
  'source': 'IMPORT',
  'duty_unit': 'İnşaat Mühendisliği',
  'cadre_unit': 'İnşaat Mühendisliği',
  'dept_code': 'CE'},
 {'full_name': 'Miray Batıkan KANDEMİR',
  'title': 'Arş. Gör.',
  'normalized_name': 'miray batıkan kandemir',
  'email': 'batikankandemir@mu.edu.tr',
  'is_external': False,
  'source': 'IMPORT',
  'duty_unit': 'Metalurji Ve Malzeme Mühendisliği',
  'cadre_unit': 'Metalurji Ve Malzeme Mühendisliği',
  'dept_code': 'MME'},
 {'full_name': 'Murat GÜL',
  'title': 'Prof. Dr.',
  'normalized_name': 'murat gül',
  'email': 'muratgul@mu.edu.tr',
  'is_external': False,
  'source': 'IMPORT',
  'duty_unit': 'İnşaat Mühendisliği',
  'cadre_unit': 'Jeoloji Mühendisliği',
  'dept_code': 'CE'},
 {'full_name': 'Mustafa ÇIRAK',
  'title': 'Doç. Dr.',
  'normalized_name': 'mustafa çırak',
  'email': 'mustafacirak@mu.edu.tr',
  'is_external': False,
  'source': 'IMPORT',
  'duty_unit': 'Maden Mühendisliği',
  'cadre_unit': 'Maden Mühendisliği',
  'dept_code': 'MINE'},
 {'full_name': 'Ömürden GENÇ',
  'title': 'Doç. Dr.',
  'normalized_name': 'ömürden genç',
  'email': 'ogenc@mu.edu.tr',
  'is_external': False,
  'source': 'IMPORT',
  'duty_unit': 'Maden Mühendisliği',
  'cadre_unit': 'Maden Mühendisliği',
  'dept_code': 'MINE'},
 {'full_name': 'Onur Can KARABULUT',
  'title': 'Arş. Gör.',
  'normalized_name': 'onur can karabulut',
  'email': 'onurcankarabulut@mu.edu.tr',
  'is_external': False,
  'source': 'IMPORT',
  'duty_unit': 'Bilgisayar Mühendisliği',
  'cadre_unit': 'Bilgisayar Mühendisliği',
  'dept_code': 'CENG'},
 {'full_name': 'Onur OKUR',
  'title': 'Dr. Öğr. Üyesi',
  'normalized_name': 'onur okur',
  'email': 'onurokur@mu.edu.tr',
  'is_external': False,
  'source': 'IMPORT',
  'duty_unit': 'Metalurji Ve Malzeme Mühendisliği',
  'cadre_unit': 'Metalurji Ve Malzeme Mühendisliği',
  'dept_code': 'MME'},
 {'full_name': 'Onur TOYGAR',
  'title': 'Dr. Öğr. Üyesi',
  'normalized_name': 'onur toygar',
  'email': 'onurtoygar@mu.edu.tr',
  'is_external': False,
  'source': 'IMPORT',
  'duty_unit': 'İnşaat Mühendisliği',
  'cadre_unit': 'İnşaat Mühendisliği',
  'dept_code': 'CE'},
 {'full_name': 'Osman KAYA',
  'title': 'Dr. Öğr. Üyesi',
  'normalized_name': 'osman kaya',
  'email': 'osmankaya@mu.edu.tr',
  'is_external': False,
  'source': 'IMPORT',
  'duty_unit': 'İnşaat Mühendisliği',
  'cadre_unit': 'İnşaat Mühendisliği',
  'dept_code': 'CE'},
 {'full_name': 'Övgü ÖZTÜRK ERGÜN',
  'title': 'Dr. Öğr. Üyesi',
  'normalized_name': 'övgü öztürk ergün',
  'email': 'ovguozturk@mu.edu.tr',
  'is_external': False,
  'source': 'IMPORT',
  'duty_unit': 'Yazılım Mühendisliği',
  'cadre_unit': 'Yazılım Mühendisliği',
  'dept_code': 'SE'},
 {'full_name': 'Özer ZEYBEK',
  'title': 'Doç. Dr.',
  'normalized_name': 'özer zeybek',
  'email': 'ozerzeybek@mu.edu.tr',
  'is_external': False,
  'source': 'IMPORT',
  'duty_unit': 'İnşaat Mühendisliği',
  'cadre_unit': 'İnşaat Mühendisliği',
  'dept_code': 'CE'},
 {'full_name': 'Özgür KILIÇ',
  'title': 'Dr. Öğr. Üyesi',
  'normalized_name': 'özgür kılıç',
  'email': 'ozgurkilic@mu.edu.tr',
  'is_external': False,
  'source': 'IMPORT',
  'duty_unit': 'Bilgisayar Mühendisliği',
  'cadre_unit': 'Bilgisayar Mühendisliği',
  'dept_code': 'CENG'},
 {'full_name': 'Özlem KASAP KESKİN',
  'title': 'Dr. Öğr. Üyesi',
  'normalized_name': 'özlem kasap keskin',
  'email': 'okasapkeskin@mu.edu.tr',
  'is_external': False,
  'source': 'IMPORT',
  'duty_unit': 'İnşaat Mühendisliği',
  'cadre_unit': 'İnşaat Mühendisliği',
  'dept_code': 'CE'},
 {'full_name': 'Petek YILDIZ SARI',
  'title': 'Öğr. Gör.',
  'normalized_name': 'petek yıldız sarı',
  'email': 'petekyildiz@mu.edu.tr',
  'is_external': False,
  'source': 'IMPORT',
  'duty_unit': 'Bilgisayar Mühendisliği',
  'cadre_unit': 'Bilgisayar Mühendisliği',
  'dept_code': 'CENG'},
 {'full_name': 'Pınar DOĞAN',
  'title': 'Prof. Dr.',
  'normalized_name': 'pınar doğan',
  'email': 'pinardogan@mu.edu.tr',
  'is_external': False,
  'source': 'IMPORT',
  'duty_unit': 'Elektrik Elektronik Mühendisliği',
  'cadre_unit': 'Elektrik Elektronik Mühendisliği',
  'dept_code': 'EEE'},
 {'full_name': 'Rıdvan KESKİN',
  'title': 'Dr. Öğr. Üyesi',
  'normalized_name': 'rıdvan keskin',
  'email': 'ridvankeskin@mu.edu.tr',
  'is_external': False,
  'source': 'IMPORT',
  'duty_unit': 'Elektrik Elektronik Mühendisliği',
  'cadre_unit': 'Elektrik Elektronik Mühendisliği',
  'dept_code': 'EEE'},
 {'full_name': 'Saleh ABDALLA',
  'title': 'Prof. Dr.',
  'normalized_name': 'saleh abdalla',
  'email': 'salehabdalla@mu.edu.tr',
  'is_external': False,
  'source': 'IMPORT',
  'duty_unit': 'İnşaat Mühendisliği',
  'cadre_unit': 'İnşaat Mühendisliği',
  'dept_code': 'CE'},
 {'full_name': 'Salih Serkan ARTAGAN',
  'title': 'Dr. Öğr. Üyesi',
  'normalized_name': 'salih serkan artagan',
  'email': 'salihserkanartagan@mu.edu.tr',
  'is_external': False,
  'source': 'IMPORT',
  'duty_unit': 'İnşaat Mühendisliği',
  'cadre_unit': 'İnşaat Mühendisliği',
  'dept_code': 'CE'},
 {'full_name': 'Selahattin AKSOY',
  'title': 'Arş. Gör.',
  'normalized_name': 'selahattin aksoy',
  'email': 'selahattinaksoy@mu.edu.tr',
  'is_external': False,
  'source': 'IMPORT',
  'duty_unit': 'Bilgisayar Mühendisliği',
  'cadre_unit': 'Bilgisayar Mühendisliği',
  'dept_code': 'CENG'},
 {'full_name': 'Selda DURMAZ DEMİR',
  'title': 'Araş.Gör.Dr.',
  'normalized_name': 'selda durmaz demir',
  'email': 'seldadurmaz@mu.edu.tr',
  'is_external': False,
  'source': 'IMPORT',
  'duty_unit': 'İnşaat Mühendisliği',
  'cadre_unit': 'İnşaat Mühendisliği',
  'dept_code': 'CE'},
 {'full_name': 'Selim YILMAZ',
  'title': 'Doç. Dr.',
  'normalized_name': 'selim yılmaz',
  'email': 'selimyilmaz@mu.edu.tr',
  'is_external': False,
  'source': 'IMPORT',
  'duty_unit': 'Yazılım Mühendisliği',
  'cadre_unit': 'Yazılım Mühendisliği',
  'dept_code': 'SE'},
 {'full_name': 'Serap ALTIN KAYA',
  'title': 'Öğr. Gör. Dr.',
  'normalized_name': 'serap altın kaya',
  'email': 'serapaltin@mu.edu.tr',
  'is_external': False,
  'source': 'IMPORT',
  'duty_unit': 'Sürdürülebilir Yeşil Kampüs Koordinatörlüğü',
  'cadre_unit': 'İnşaat Mühendisliği',
  'dept_code': 'CE'},
 {'full_name': 'Süleyman Bahadır KESKİN',
  'title': 'Dr. Öğr. Üyesi',
  'normalized_name': 'süleyman bahadır keskin',
  'email': 'sbkeskin@mu.edu.tr',
  'is_external': False,
  'source': 'IMPORT',
  'duty_unit': 'İnşaat Mühendisliği',
  'cadre_unit': 'İnşaat Mühendisliği',
  'dept_code': 'CE'},
 {'full_name': 'Taki GÜLER',
  'title': 'Prof. Dr.',
  'normalized_name': 'taki güler',
  'email': 'takiguler@mu.edu.tr',
  'is_external': False,
  'source': 'IMPORT',
  'duty_unit': 'Maden Mühendisliği',
  'cadre_unit': 'Maden Mühendisliği',
  'dept_code': 'MINE'},
 {'full_name': 'Tuğba SÜZEK',
  'title': 'Doç. Dr.',
  'normalized_name': 'tuğba süzek',
  'email': 'tugbasuzek@mu.edu.tr',
  'is_external': False,
  'source': 'IMPORT',
  'duty_unit': 'Bilgisayar Mühendisliği',
  'cadre_unit': 'Bilgisayar Mühendisliği',
  'dept_code': 'CENG'},
 {'full_name': 'Uğur Can ÖZÖĞÜT',
  'title': 'Öğr. Gör.',
  'normalized_name': 'uğur can özöğüt',
  'email': 'ucozogut@mu.edu.tr',
  'is_external': False,
  'source': 'IMPORT',
  'duty_unit': 'Metalurji Ve Malzeme Mühendisliği',
  'cadre_unit': 'Metalurji Ve Malzeme Mühendisliği',
  'dept_code': 'MME'},
 {'full_name': 'Yaşar ORBAY',
  'title': 'Arş. Gör.',
  'normalized_name': 'yaşar orbay',
  'email': 'yasarorbay@mu.edu.tr',
  'is_external': False,
  'source': 'IMPORT',
  'duty_unit': 'Metalurji Ve Malzeme Mühendisliği',
  'cadre_unit': 'Metalurji Ve Malzeme Mühendisliği',
  'dept_code': 'MME'},
 {'full_name': 'Yelda MEYVA ZEYBEK',
  'title': 'Dr. Öğr. Üyesi',
  'normalized_name': 'yelda meyva zeybek',
  'email': 'yeldameyvazeybek@mu.edu.tr',
  'is_external': False,
  'source': 'IMPORT',
  'duty_unit': 'Metalurji Ve Malzeme Mühendisliği',
  'cadre_unit': 'Metalurji Ve Malzeme Mühendisliği',
  'dept_code': 'MME'},
 {'full_name': 'Yılmaz Öğünç TETİK',
  'title': 'Araş.Gör.Dr.',
  'normalized_name': 'yılmaz öğünç tetik',
  'email': 'yilmazogunctetik@mu.edu.tr',
  'is_external': False,
  'source': 'IMPORT',
  'duty_unit': 'İnşaat Mühendisliği',
  'cadre_unit': 'İnşaat Mühendisliği',
  'dept_code': 'CE'},
 {'full_name': 'Zeki Bora ÖN',
  'title': 'Dr. Öğr. Üyesi',
  'normalized_name': 'zeki bora ön',
  'email': 'boraon@mu.edu.tr',
  'is_external': False,
  'source': 'IMPORT',
  'duty_unit': 'Elektrik Elektronik Mühendisliği',
  'cadre_unit': 'Elektrik Elektronik Mühendisliği',
  'dept_code': 'EEE'},
 {'full_name': 'Zeynep Filiz EREN',
  'title': 'Dr. Öğr. Üyesi',
  'normalized_name': 'zeynep filiz eren',
  'email': 'zeynepfilizeren@mu.edu.tr',
  'is_external': False,
  'source': 'IMPORT',
  'duty_unit': 'Bilgisayar Mühendisliği',
  'cadre_unit': 'Bilgisayar Mühendisliği',
  'dept_code': 'CENG'},
 {'full_name': 'Zeynep Yıldız',
  'title': 'Öğr. Gör.',
  'normalized_name': 'zeynep yıldız',
  'email': None,
  'is_external': True,
  'source': 'MANUAL',
  'duty_unit': None,
  'cadre_unit': None,
  'dept_code': 'CE'}]

# Kısıtlı yetki testleri için alt hesap: yalnız derslik + öğretim üyesi
# yönetebilir; ders/haftalık/sınav yönetimi ve admin ekranları (Dashboard,
# Kullanıcılar) KAPALI.
SUB_ACCOUNT = {
    "name": "Alt Hesap (Test)",
    "email": "althesap@muh.example.edu.tr",
    "password": "test1234",
    "can_manage_courses": False,
    "can_manage_weekly": False,
    "can_manage_exams": False,
    "can_manage_classrooms": True,
    "can_manage_lecturers": True,
}


def seed_engineering():
    db = SessionLocal()
    try:
        wg = db.query(Workgroup).first()
        if wg is None:
            wg = Workgroup(name="Mühendislik Fakültesi",
                           allowed_email_domain="muh.example.edu.tr")
            db.add(wg)
            db.flush()
        admin = db.query(User).filter(User.role == UserRole.ADMIN).first()
        if admin is not None and wg.created_by is None:
            wg.created_by = admin.id

        # --- Bölümler (koda göre idempotent) ---
        dep_by_code = {}
        for d in DEPARTMENTS:
            existing = db.query(Department).filter(Department.code == d["code"]).first()
            if existing is None:
                existing = Department(workgroup_id=wg.id, code=d["code"], name=d["name"])
                db.add(existing)
                db.flush()
                print(f"Bölüm eklendi: {d['code']} — {d['name']}")
            dep_by_code[d["code"]] = existing

        # --- Öğretim üyeleri (normalized_name'e göre idempotent) ---
        eklendi = 0
        for l in LECTURERS:
            clash = db.query(Lecturer).filter(
                Lecturer.workgroup_id == wg.id,
                Lecturer.normalized_name == l["normalized_name"],
            ).first()
            if clash is not None:
                continue
            dep = dep_by_code.get(l["dept_code"]) if l["dept_code"] else None
            db.add(Lecturer(
                workgroup_id=wg.id,
                full_name=l["full_name"],
                title=l["title"],
                normalized_name=l["normalized_name"],
                email=l["email"],
                is_external=l["is_external"],
                source=l["source"],
                department_id=dep.id if dep else None,
                duty_unit=l["duty_unit"],
                cadre_unit=l["cadre_unit"],
            ))
            eklendi += 1
        print(f"Öğretim üyesi: {eklendi} yeni eklendi, {len(LECTURERS) - eklendi} zaten vardı.")

        # --- Test alt hesabı ---
        if db.query(User).filter(User.email == SUB_ACCOUNT["email"]).first() is None:
            db.add(User(
                workgroup_id=wg.id,
                name=SUB_ACCOUNT["name"],
                email=SUB_ACCOUNT["email"],
                password_hash=hash_password(SUB_ACCOUNT["password"]),
                role=UserRole.SUB_ACCOUNT,
                status=UserStatus.ACTIVE,
                can_manage_courses=SUB_ACCOUNT["can_manage_courses"],
                can_manage_weekly=SUB_ACCOUNT["can_manage_weekly"],
                can_manage_exams=SUB_ACCOUNT["can_manage_exams"],
                can_manage_classrooms=SUB_ACCOUNT["can_manage_classrooms"],
                can_manage_lecturers=SUB_ACCOUNT["can_manage_lecturers"],
            ))
            print(f"Alt hesap eklendi: {SUB_ACCOUNT['email']} / {SUB_ACCOUNT['password']}")

        db.commit()
        print("seed_engineering tamam.")
    finally:
        db.close()


if __name__ == "__main__":
    seed_engineering()
