"""K-30 buildings.is_external

Revision ID: 295cea40dd89
Revises: f35895a406f4
Create Date: 2026-07-21 15:18:19.979711

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '295cea40dd89'
down_revision: Union[str, None] = 'f35895a406f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('buildings', sa.Column('is_external', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('buildings', 'is_external')
    # ### end Alembic commands ###
