"""wp0 initial schema

Revision ID: c33ba85c0ae1
Revises: 
Create Date: 2026-07-09 18:55:17.241014

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c33ba85c0ae1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('slots',
    sa.Column('slot_no', sa.SmallInteger(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.CheckConstraint('slot_no BETWEEN 1 AND 9', name='ck_slots_range'),
    sa.PrimaryKeyConstraint('slot_no')
    )
    op.create_table('workgroups',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('type', sa.String(length=50), server_default=sa.text("'FACULTY'"), nullable=False),
    sa.Column('allowed_email_domain', sa.String(length=100), nullable=False),
    sa.Column('check_exam_vs_course', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('classrooms',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('workgroup_id', sa.BigInteger(), nullable=False),
    sa.Column('building', sa.String(length=100), nullable=False),
    sa.Column('room_code', sa.String(length=30), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.CheckConstraint('capacity > 0', name='ck_classrooms_capacity_positive'),
    sa.ForeignKeyConstraint(['workgroup_id'], ['workgroups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workgroup_id', 'building', 'room_code', name='uq_classrooms_location')
    )
    op.create_table('departments',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('workgroup_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['workgroup_id'], ['workgroups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workgroup_id', 'code', name='uq_departments_workgroup_code')
    )
    op.create_table('lecturers',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('workgroup_id', sa.BigInteger(), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('normalized_name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=True),
    sa.Column('is_external', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('source', sa.String(length=20), server_default=sa.text("'IMPORT'"), nullable=False),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.ForeignKeyConstraint(['workgroup_id'], ['workgroups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workgroup_id', 'normalized_name', name='uq_lecturers_workgroup_normname')
    )
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('workgroup_id', sa.BigInteger(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('role', sa.Enum('ADMIN', 'SUB_ACCOUNT', name='user_role'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACTIVE', 'DISABLED', name='user_status'), server_default=sa.text("'PENDING'"), nullable=False),
    sa.Column('can_manage_classrooms', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workgroup_id'], ['workgroups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('action', sa.String(length=10), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('courses',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('department_id', sa.BigInteger(), nullable=False),
    sa.Column('year', sa.SmallInteger(), nullable=False),
    sa.Column('semester', sa.Enum('FALL', 'SPRING', 'SUMMER', name='semester_type'), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('section_no', sa.SmallInteger(), server_default=sa.text('1'), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('lecturer_id', sa.BigInteger(), nullable=False),
    sa.Column('expected_students', sa.Integer(), nullable=False),
    sa.Column('is_elective', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('default_classroom_id', sa.BigInteger(), nullable=True),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.CheckConstraint('expected_students > 0', name='ck_courses_expected_positive'),
    sa.CheckConstraint('section_no > 0', name='ck_courses_section_positive'),
    sa.CheckConstraint('year BETWEEN 1 AND 6', name='ck_courses_year_range'),
    sa.ForeignKeyConstraint(['default_classroom_id'], ['classrooms.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lecturer_id'], ['lecturers.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('department_id', 'year', 'semester', 'code', 'section_no', name='uq_courses_identity')
    )
    op.create_table('department_memberships',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('department_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'department_id')
    )
    op.create_table('invitation_tokens',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_table('exams',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('course_id', sa.BigInteger(), nullable=False),
    sa.Column('exam_type', sa.Enum('MIDTERM', 'FINAL', 'MAKEUP', name='exam_type'), nullable=False),
    sa.Column('exam_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('classroom_id', sa.BigInteger(), nullable=True),
    sa.Column('lecturer_id', sa.BigInteger(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'SUBMITTED', name='entry_status'), server_default=sa.text("'DRAFT'"), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(status = 'SUBMITTED') = (submitted_at IS NOT NULL)", name='ck_exams_status_submitted_consistency'),
    sa.CheckConstraint('EXTRACT(ISODOW FROM exam_date) BETWEEN 1 AND 5', name='ck_exams_weekday_only'),
    sa.ForeignKeyConstraint(['classroom_id'], ['classrooms.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lecturer_id'], ['lecturers.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course_id', 'exam_type', name='uq_exams_course_type')
    )
    op.create_index('idx_exams_classroom_date', 'exams', ['classroom_id', 'exam_date'], unique=False)
    op.create_index('idx_exams_date', 'exams', ['exam_date'], unique=False)
    op.create_index('idx_exams_status', 'exams', ['status'], unique=False)
    op.create_table('weekly_schedule_entries',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('course_id', sa.BigInteger(), nullable=False),
    sa.Column('classroom_id', sa.BigInteger(), nullable=True),
    sa.Column('day_of_week', sa.SmallInteger(), nullable=False),
    sa.Column('start_slot', sa.SmallInteger(), nullable=False),
    sa.Column('slot_count', sa.SmallInteger(), server_default=sa.text('1'), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'SUBMITTED', name='entry_status'), server_default=sa.text("'DRAFT'"), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(status = 'SUBMITTED') = (submitted_at IS NOT NULL)", name='ck_wse_status_submitted_consistency'),
    sa.CheckConstraint('start_slot + slot_count - 1 <= 9', name='ck_wse_slot_overflow'),
    sa.ForeignKeyConstraint(['classroom_id'], ['classrooms.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_wse_classroom_day', 'weekly_schedule_entries', ['classroom_id', 'day_of_week'], unique=False)
    op.create_index('idx_wse_course', 'weekly_schedule_entries', ['course_id'], unique=False)
    op.create_index('idx_wse_status', 'weekly_schedule_entries', ['status'], unique=False)

    # --- ELLE EKLENDI ---
    # 1) Dairesel FK (use_alter inline birakilinca hic uretilmiyordu):
    op.create_foreign_key(
        'fk_workgroups_created_by', 'workgroups', 'users',
        ['created_by'], ['id'], ondelete='SET NULL',
    )
    # 2) slots referans tablosu seed verisi (autogenerate veri eklemez):
    op.execute(
        """
        INSERT INTO slots (slot_no, start_time, end_time) VALUES
        (1,'08:30','09:15'),(2,'09:30','10:15'),(3,'10:30','11:15'),
        (4,'11:30','12:15'),(5,'12:30','13:15'),(6,'13:30','14:15'),
        (7,'14:30','15:15'),(8,'15:30','16:15'),(9,'16:30','17:15')
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # ELLE EKLENDI: once dairesel FK'yi dusur (tablolari silebilmek icin).
    op.drop_constraint('fk_workgroups_created_by', 'workgroups', type_='foreignkey')
    op.drop_index('idx_wse_status', table_name='weekly_schedule_entries')
    op.drop_index('idx_wse_course', table_name='weekly_schedule_entries')
    op.drop_index('idx_wse_classroom_day', table_name='weekly_schedule_entries')
    op.drop_table('weekly_schedule_entries')
    op.drop_index('idx_exams_status', table_name='exams')
    op.drop_index('idx_exams_date', table_name='exams')
    op.drop_index('idx_exams_classroom_date', table_name='exams')
    op.drop_table('exams')
    op.drop_table('invitation_tokens')
    op.drop_table('department_memberships')
    op.drop_table('courses')
    op.drop_table('audit_logs')
    op.drop_table('users')
    op.drop_table('lecturers')
    op.drop_table('departments')
    op.drop_table('classrooms')
    op.drop_table('workgroups')
    op.drop_table('slots')
    # ELLE EKLENDI: enum tiplerini de dusur (autogenerate birakiyor).
    op.execute("DROP TYPE IF EXISTS entry_status")
    op.execute("DROP TYPE IF EXISTS exam_type")
    op.execute("DROP TYPE IF EXISTS semester_type")
    op.execute("DROP TYPE IF EXISTS user_status")
    op.execute("DROP TYPE IF EXISTS user_role")
    # ### end Alembic commands ###
