"""K-25 yetenek bayraklari

Revision ID: f35895a406f4
Revises: e5cf77db619f
Create Date: 2026-07-19 13:44:23.077912

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f35895a406f4'
down_revision: Union[str, None] = 'e5cf77db619f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('can_manage_courses', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('users', sa.Column('can_manage_weekly', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('users', sa.Column('can_manage_exams', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('users', sa.Column('can_manage_lecturers', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'can_manage_lecturers')
    op.drop_column('users', 'can_manage_exams')
    op.drop_column('users', 'can_manage_weekly')
    op.drop_column('users', 'can_manage_courses')
    # ### end Alembic commands ###
